image: node:alpine

stages:
  - unitTest
  - build
  - deploy

Test:
  stage: unitTest
  cache:
    paths:
      - node_modules
  before_script:
    - ls
    - npm i
  script:
    - ls
    - echo "---- Unit Test ----"
    - npm run test # jest

Build:
  stage: build
  # only:
  #   - master
  cache:
    paths:
      - node_modules
  script:
    - echo "---- Layer Install ----"
    - npm i -g ts-node
    - ts-node lib/process/setup.ts
    - echo "---- Build ----"
    - npm run build

Deploy:
  stage: deploy
  # only:
  #   - master
  cache:
    paths:
      - node_modules
  script:
    - echo "---- Deploy ----"
    - cdk deploy
