image: node:alpine

stages:
  - unitTest
  - build
  - deployDev
  - deployPro

Test:
  stage: unitTest
  cache:
    paths:
      - node_modules
  before_script:
    - ls
    - npm i
  script:
    - ls
    - echo "---- Unit Test ----"
    - npm run test # jest

Build:
  stage: build
  rules:
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"' # masterにpushされている場合のみ
      when: always # 直前のステージでジョブの状態がどうであるかにかかわらずジョブを実行
    - if: "$VAR =~ /pattern/"
      when: manual # ジョブを手動で実行
    - when: on_success # 直前のジョブが全て成功した場合にのみジョブが実行
  cache:
    paths:
      - node_modules
  script:
    - echo "---- Layer Install ----"
    - npm i -g ts-node
    - ts-node lib/process/setup.ts
    - echo "---- Build ----"
    - npm run build

DeployDev:
  stage: deploy
  rules:
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"'
      when: always
    - if: "$VAR =~ /pattern/"
      when: manual
    - when: on_success
  cache:
    paths:
      - node_modules
  script:
    - echo "---- Deploy ----"
    - cdk deploy SYSTEM_ENV=dev # 環境変数で環境を分岐させる

DeployPro:
  stage: deploy
  rules:
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"'
      when: manual # 本番環境へのデプロイは手動実行にする
  cache:
    paths:
      - node_modules
  script:
    - echo "---- Deploy ----"
    - cdk deploy SYSTEM_ENV=pro
