stages:
  - unitTest
  - build
  - deploy

Test:
  stage: unitTest
  script:
    - npm run test # jest
  only: # masterにpushされた時のみにする
    - pushes

Build:
  stage: build
  script:
    - npm run build

Deploy:
  stage: deploy
  script:
    - cdk deploy
