# image: node:alpine
image: node:latest

# variables:
#   DEST_DIR: dest/

stages:
  - unitTest
  - build
  - deployDev
  - deployPro

# https://qiita.com/mstssk/items/8759c71f328cab802670
# .~/npmをnpmはキャッシュ先のディレクトリとして使用するが、node_modulesをキャッシュした方が早そう
# https://qiita.com/qrusadorz/items/937d97b177cb0140d1eb
# cache: # https://gitlab-docs.creationline.com/ee/ci/caching/#caching-nodejs-dependencies
#   key: ${CI_COMMIT_REF_SLUG}
#   paths:
#     - .npm/

# before_script:
#   - npm ci --cache .npm --prefer-offline

include: # 重複したパイプラインの作成を防ぐため
  - template: "Workflows/MergeRequest-Pipelines.gitlab-ci.yml"

Test:
  stage: unitTest
  rules: #if: '$CI_PIPELINE_SOURCE == "push"' # pushされた場合
    - when: always # 直前のステージでジョブの状態がどうであるかにかかわらずジョブを実行
  cache:
    key:
      ${CI_COMMIT_REF_SLUG} # 同じブランチでは同じキャッシュを使用
      # files:
      #   - package.json # 依存関係が変更される度にキャッシュを更新するようにする
    paths:
      - node_modules
  before_script: #pwd => builds/sakurai-ryo/projectName
    - ls
    - npm ci --progress=false # テストに必要なモジュールのインストール
    - mkdir -p dist dist/handler bundle bundle/nodejs
  script:
    - echo "---- Unit Test ----"
    - npm run test # jest

Build:
  stage: build
  rules:
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"'
      when: on_success
    # - if: '$CI_COMMIT_BRANCH == "master"' # masterへのpushの場合
    #   when: on_success # testが通った時のみ実行する
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    # files:
    #   - package.json # 依存関係が変更される度にキャッシュを更新するようにする
    paths:
      - bundle/nodejs/node_modules # layerに使用するnode_modulesをキャッシュ
      - node_modules
  artifacts: # webpackでbundleしたファイル次に引き継ぐ
    paths:
      - dist/
  before_script:
    - ls
  script:
    - echo "---- Layer Install ----"
    - npx ts-node process/setup.ts # package.jsonのdependenciesのみをインストール
    - echo "---- Build ----"
    - npm run build

DeployDev:
  stage: deployDev
  rules:
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"'
      when: on_success
    # - if: '$CI_COMMIT_BRANCH == "master"'
    #   when: on_success # test & buildが成功した時のみ
  dependencies:
    - Build
  before_script:
    - ls
    - npm config set prefix /usr/local
    - npm ci -g aws-cdk
  script:
    - echo "---- Deploy ----"
    - SYSTEM_ENV=dev npm run deploy # 環境変数で環境を分岐させる

DeployPro:
  stage: deployPro
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: manual # 本番環境へのデプロイは手動実行にする
  dependencies:
    - Build
  script:
    - echo "---- Deploy ----"
    - SYSTEM_ENV=pro npm run deploy
