# image: node:alpine

# stages:
#   - unitTest
#   - build
#   - deploy

# cache:
#   paths:
#     - node_modules

Test:
  stage: unitTest
  before_script:
    - npm i -g jest aws-cdk
  script:
    - ls
    - echo "---- Unit Test ----"
    - npm run test # jest

Build:
  stage: build
  # only:
  #   - master
  before_script:
    - npm i -g webpack ts-loader webpack-node-externals
  script:
    - echo "---- Build ----"
    - npm run build

Deploy:
  stage: deploy
  # only:
  #   - master
  # before_script:
  #   - npm i -g aws-cdk
  script:
    - echo "---- Deploy ----"
    - cdk deploy
